### ISSUE TITLE
Trucraft + unified_inventory turns off creative

### ISSUE THREAD

**Issue by RichardTry** [PolySaken-I-Am/trucraft#1]
If unified_inventory turned on, digging with hand and far interact distance (things given by creative) are turns off.
#### Steps to reproduce:
1) Create world or choose existing
2) Turn on trucraft
3) Turn on unified_unventory
4) Tick the "creative" checkbox
5) Make sure you can't break a stone with your hand

**Comment by PolySaken-I-Am** [comment]
This is intentional. If It didn't do this, the survival aspect wouln't work. (trucraft is meant for survival only anyway so conflicts with creative mode aren't on my list of things to consider.)
